package ar.edu.itba.instruII.views

import android.sax.Element
import android.widget.AutoCompleteTextView
import ar.edu.itba.instruII.R
import kotlinx.android.synthetic.main.activity_calculadora.*

class ValidacionAlimentos{

    fun main (args: Array<String>){

        var hset : HashSet<String> = HashSet()
        hset.add("Flan (unidad)")
        hset.add("Helado de crema (bocha)")
        hset.add("Helado de agua (unidad)")
        hset.add("Leche descremada (vaso o taza)")
        hset.add("Leche entera (vaso o taza)")
        hset.add("Crema de leche (brick)")
        hset.add("Queso fresco")
        hset.add("Yogurt entero (unidad)")
        hset.add("Yogurt descremado (unidad)")
        hset.add("Yogurt líquido (unidad)")
        hset.add("Arroz (plato mediano)")
        hset.add("Arroz (plato grande)")
        hset.add("Arroz (guarnición)")
        hset.add("Arroz integral (plato mediano)")
        hset.add("Arroz integral (plato grande)")
        hset.add("Arroz integral (guarnición)")
        hset.add("Batata")
        hset.add("Galleta (unidad)")
        hset.add("Guisantes (plato mediano)")
        hset.add("Guisantes (plato grande)")
        hset.add("Guisantes (guarnición)")
        hset.add("Harina de trigo/maíz (cucharada sopera)")
        hset.add("Lentejas (plato mediano)")
        hset.add("Lentejas (plato grande)")
        hset.add("Lentejas (guarnición)")
        hset.add("Pan blanco (rebanada)")
        hset.add("Papa hervida (plato mediano)")
        hset.add("Papa hervida (plato grande)")
        hset.add("Papa hervida (guarnición)")
        hset.add("Papas fritas (guarnición)")
        hset.add("Sushi")
        hset.add("Palta")
        hset.add("Albaricoque")
        hset.add("Arándano (puñado)")
        hset.add("Castaña (unidad)")
        hset.add("Cereza (12 unidades)")
        hset.add("Ciruela")
        hset.add("Coco (tajada)")
        hset.add("Dátil")
        hset.add("Frambuesa (puñado)")
        hset.add("Higos")
        hset.add("Kiwi")
        hset.add("Limón")
        hset.add("Mandarina")
        hset.add("Mango")
        hset.add("Manzana")
        hset.add("Durazno")
        hset.add("Durazno en conserva (una mitad)")
        hset.add("Melón (tajada)")
        hset.add("Membrillo")
        hset.add("Moras (puñado)")
        hset.add("Naranja")
        hset.add("Pera")
        hset.add("Papaya (tajada)")
        hset.add("Ananá (2 rodajas)")
        hset.add("Banana")
        hset.add("Sandía (tajada)")
        hset.add("Uva (12 unidades)")
        hset.add("Acelga")
        hset.add("Ajo (3 dientes)")
        hset.add("Alcachofa")
        hset.add("Berenjena")
        hset.add("Berro")
        hset.add("Brócoli")
        hset.add("Calabacín")
        hset.add("Cebolla")
        hset.add("Champiñón")
        hset.add("Coliflor")
        hset.add("Escarola")
        hset.add("Espárrago")
        hset.add("Espinaca")
        hset.add("Lechuga")
        hset.add("Nabo")
        hset.add("Palmitos")
        hset.add("Pepino")
        hset.add("Morrón rojo/verde")
        hset.add("Puerro")
        hset.add("Rábano")
        hset.add("Repollo")
        hset.add("Tomate")
        hset.add("Zanahoria cruda")
        hset.add("Zanahoria cocida")
        hset.add("Aceituna (12 unidades)")
        hset.add("Almendra (puñado)")
        hset.add("Avellana (puñado)")
        hset.add("Maní (puñado)")
        hset.add("Pasas de uva (puñado)")
        hset.add("Nuez (puñado)")
        hset.add("Pipas (puñado)")
        hset.add("Pistacho (puñado)")
        hset.add("Gaseosa (vaso)")
        hset.add("Gaseosa light (vaso)")
        hset.add("Chocolatada (vaso)")
        hset.add("Bebida energética (lata)")
        hset.add("Cerveza (vaso)")
        hset.add("Sidra (copa)")
        hset.add("Vermut (copa)")
        hset.add("Jugo de frutas (vaso)")
        hset.add("Vino (copa)")
        hset.add("Azúcar blanca (cucharada de postre)")
        hset.add("Azúcar negra (cucharada de postre)")
        hset.add("Barra de cereales")
        hset.add("Croissant (unidad)")
        hset.add("Cacao en polvo (cucharada de postre)")
        hset.add("Canelones (3 unidades)")
        hset.add("Caramelo (unidad)")
        hset.add("Chocolate (tableta)")
        hset.add("Empanada")
        hset.add("Edulcorante (cucharada sopera)")
        hset.add("Gelatina")
        hset.add("Ketchup (sobre)")
        hset.add("Lasaña")
        hset.add("Magdalena")
        hset.add("Mermelada (cucharada sopera)")
        hset.add("Mermelada light (cucharada sopera)")
        hset.add("Miel (cucharada sopera)")
        hset.add("Mostaza")
        hset.add("Pizza (porción)")
        hset.add("Salsa barbacoa")
        hset.add("Salsa blanca")
        hset.add("Salsa bolognesa")
        hset.add("Salsa de tomate")
        hset.add("Vinagre")
        hset.add("Fideos (plato mediano)")
        hset.add("Fideos (plato grande)")
        hset.add("Fideos (guarnición)")
        hset.add("Torta de bizcochuelo (porción)")

    }

}